const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));

const musicToggle=document.getElementById("musicToggle"),homeMusic=document.getElementById("homeMusic");
if(homeMusic){const musicEnabled=()=>localStorage.getItem("claraMusicEnabled")==="true";const savedMusicTime=Number(localStorage.getItem("claraMusicTime")||0);const restoreMusicTime=()=>{if(Number.isFinite(savedMusicTime)&&savedMusicTime>0&&savedMusicTime<homeMusic.duration)homeMusic.currentTime=savedMusicTime;};const saveMusicTime=()=>{if(Number.isFinite(homeMusic.currentTime))localStorage.setItem("claraMusicTime",String(homeMusic.currentTime));};const startHomeMusic=()=>{if(musicEnabled())homeMusic.play().catch(()=>{});};homeMusic.addEventListener("loadedmetadata",restoreMusicTime,{once:true});homeMusic.addEventListener("timeupdate",saveMusicTime);window.addEventListener("pagehide",saveMusicTime);if(musicToggle){musicToggle.checked=musicEnabled();musicToggle.onchange=()=>{localStorage.setItem("claraMusicEnabled",String(musicToggle.checked));if(musicToggle.checked)startHomeMusic();else{homeMusic.pause();homeMusic.currentTime=0;localStorage.removeItem("claraMusicTime");}};}startHomeMusic();document.addEventListener("pointerdown",startHomeMusic,{once:true});}

/* FOTO / GALERIA */
const defaultPhotos=[
 {id:"p1",src:"fotos/lindinha.jpeg",title:"O Amor é Lindo",meta:"",description:"Uma das obras mais lindas feitas pela natureza, muitos devem crer que esta é uma escultura de alguma deusa grega, mas a obra se trata sobre bem mais do que isso; com olhos perfeitos, um lindo cabelo e proporções faciais quase divinas, como seu admirável nariz e seus lábios encantadores."},{id:"p2",src:"fotos/anjinho.jpeg",title:"Uma Boboca",meta:"",description:"Além de extremamente fofa também temos essa bobona aí que com certeza não me faz sorrir todos os dias que nem um idiota olhando para o celular."},{id:"p3",src:"fotos/bem.jpeg",title:"Minha Pudinzinha",meta:"",description:"Mas pode ser o que for, linda ou completamente maluca ela é MINHA pudinzinha, e eu a-amo com toda minha vida. Muito obrigado por existir meu anjinho <3"},{id:"p4",src:"fotos/eu.jpeg",title:"Aberração",meta:"",description:"Aqui temos uma aberração horrorosa diretamente de Chernobyl, misericória quero nem comentar sobre essa aqui, que bixo fei véi"},{id:"p5",src:"fotos/cat.jpeg",title:"Scuba",meta:"",description:"Nossos futuros gatos aí, oh"},{id:"p6",src:"fotos/borzoi.jpeg",title:"Nosso Futuro Cachorro",meta:"",description:"Nosso futuro cachorro aí também :D"}
];
const savedPhotos=JSON.parse(localStorage.getItem("claraPhotos")||"null");
const isOldDefault=Array.isArray(savedPhotos)&&savedPhotos.length===6&&savedPhotos.every((p,i)=>p.id===`p${i+1}`&&!p.src);
let photos=isOldDefault?defaultPhotos:(savedPhotos||defaultPhotos);
if(isOldDefault)localStorage.setItem("claraPhotos",JSON.stringify(defaultPhotos));
let favorites=JSON.parse(localStorage.getItem("claraFavorites")||"[]");
let currentPhotoId=null;
const gallery=document.getElementById("gallery");
function renderGallery(){if(!gallery)return;gallery.innerHTML="";photos.forEach((p,i)=>{const el=document.createElement("article");el.className="photo-card";el.innerHTML=p.src?`<img src="${esc(p.src)}" alt="${esc(p.title)}">`:`<div class="placeholder">PLACEHOLDER<br>FOTO ${i+1}</div>`;el.innerHTML+=`<div class="photo-title">${esc(p.title)}</div>`;el.onclick=()=>openViewer(p.id);gallery.appendChild(el);});}
function openViewer(id){const p=photos.find(x=>x.id===id);if(!p)return;currentPhotoId=id;const t=document.getElementById("viewerTitle"),m=document.getElementById("viewerMeta"),d=document.getElementById("viewerDescription"),im=document.getElementById("viewerImage"),fav=document.getElementById("favoritePhoto"),v=document.getElementById("photoViewer");if(!v)return;t.textContent=p.title;m.textContent=p.meta||"";d.textContent=p.description||"";im.innerHTML=p.src?`<img src="${esc(p.src)}" alt="${esc(p.title)}">`:"Placeholder";fav.textContent=favorites.includes(id)?"♥":"♡";v.classList.remove("hidden");}
const closeViewer=document.getElementById("closeViewer");if(closeViewer)closeViewer.onclick=()=>document.getElementById("photoViewer").classList.add("hidden");
const favoritePhoto=document.getElementById("favoritePhoto");if(favoritePhoto)favoritePhoto.onclick=()=>{favorites.includes(currentPhotoId)?favorites=favorites.filter(x=>x!==currentPhotoId):favorites.push(currentPhotoId);localStorage.setItem("claraFavorites",JSON.stringify(favorites));favoritePhoto.textContent=favorites.includes(currentPhotoId)?"♥":"♡";};
const deletePhoto=document.getElementById("deletePhoto");if(deletePhoto)deletePhoto.onclick=()=>{if(!currentPhotoId)return;photos=photos.filter(p=>p.id!==currentPhotoId);localStorage.setItem("claraPhotos",JSON.stringify(photos));document.getElementById("photoViewer").classList.add("hidden");renderGallery();};
const editor=document.getElementById("photoEditor");const addBtn=document.getElementById("addBtn");if(addBtn)addBtn.onclick=()=>editor.classList.remove("hidden");const closeEditor=document.getElementById("closeEditor");if(closeEditor)closeEditor.onclick=()=>editor.classList.add("hidden");
const photoForm=document.getElementById("photoForm");if(photoForm)photoForm.onsubmit=e=>{e.preventDefault();const file=document.getElementById("photoFile").files[0];if(!file)return;const r=new FileReader();r.onload=()=>{photos.push({id:"p"+Date.now(),src:r.result,title:document.getElementById("photoTitle").value,meta:document.getElementById("photoMeta").value,description:document.getElementById("photoDescription").value});localStorage.setItem("claraPhotos",JSON.stringify(photos));renderGallery();editor.classList.add("hidden");e.target.reset();};r.readAsDataURL(file);};
renderGallery();

/* FRASES */
let quotes=JSON.parse(localStorage.getItem("claraQuotes")||"null")||[
 {category:"Determinação",text:"A vida, não é sobre desistir, a vida, não é sobre levantar a cada queda, mas sobre continuar de pé, resistindo á balas e facas.",author:"Davi Parra, 2024"},{category:"Sacrifício",text:"Que meu sangue escorra para que o seu circule em ti.",author:"Davi Parra, 2025"},{category:"Promessa",text:"Eu esvaziaria minhas veias por você se o seu coração não tivesse sangue o suficiente.",author:"Davi Parra, 2025"},{category:"O Começo de Tudo",text:"eo sempre te infernizarei",author:"Maria Clara, 2025"}
];
const quotesList=document.getElementById("quotesList");
function renderQuotes(){if(!quotesList)return;quotesList.innerHTML="";quotes.forEach(q=>{const el=document.createElement("article");el.className="quote";el.innerHTML=`<div class="quote-category">${esc(q.category)}</div><div class="quote-text">"${esc(q.text)}"</div><div class="quote-author">- ${esc(q.author||"")}</div>`;quotesList.appendChild(el);});}
renderQuotes();
const addQuoteBtn=document.getElementById("addQuoteBtn"),quoteEditor=document.getElementById("quoteEditor");if(addQuoteBtn)addQuoteBtn.onclick=()=>quoteEditor.classList.remove("hidden");const closeQuoteEditor=document.getElementById("closeQuoteEditor");if(closeQuoteEditor)closeQuoteEditor.onclick=()=>quoteEditor.classList.add("hidden");
const quoteForm=document.getElementById("quoteForm");if(quoteForm)quoteForm.onsubmit=e=>{e.preventDefault();quotes.push({category:quoteCategory.value,text:quoteTextInput.value,author:quoteAuthor.value});localStorage.setItem("claraQuotes",JSON.stringify(quotes));renderQuotes();quoteEditor.classList.add("hidden");e.target.reset();};

/* PLAYLIST — altere esta lista para colocar suas músicas */
const songs=[{title:"Perfect - Ed Sheeran",file:"musicas/Perfect - Ed Sheeran.mp3",cover:"assets/divide.webp",description:"Resumindo você para mim."},{title:"I Was Born to Love You - Freddie Mercury",file:"musicas/I Was Born to Love You - Freddie Mercury.mp3",cover:"assets/messenger.webp",description:"A minha vida resumida á você."},{title:"I Just Can't Stop Loving You - Michael Jackson",file:"musicas/I Just Can't Stop Loving You - Michael Jackson.mp3",cover:"assets/bad.webp",description:"E EU NÃO QUERO PARAR DE TE AMAR, NUNCA!!!"},{title:"When Did You Get Hot - Sabrina Carpenter",file:"musicas/When Did You Get Hot - Sabrina Carpenter.mp3",cover:"assets/man.jpeg",description:"Quando é que você ficou tão gostosa, assim? 🫦"},{title:"Diamond In The Sky - SEGA",file:"musicas/Diamond In The Sky - SEGA.mp3",cover:"assets/race.webp",description:"Você é o meu diamante no céu <3"}];
const trackList=document.getElementById("trackList"),audio=document.getElementById("audio");
function loadSong(i){const s=songs[i];if(!s)return;document.getElementById("currentTitle").textContent=s.title;document.getElementById("currentDescription").textContent=s.description;document.getElementById("cover").innerHTML=s.cover?`<img src="${esc(s.cover)}" style="width:100%;height:100%;object-fit:cover">`:"PLACEHOLDER";audio.src=s.file;}
if(trackList&&audio){songs.forEach((s,i)=>{const row=document.createElement("div"),playButton=document.createElement("button"),title=document.createElement("button");row.className="track-row";playButton.type="button";playButton.className="track-play";playButton.textContent="▶";playButton.setAttribute("aria-label",`Tocar ${s.title}`);title.type="button";title.className="track-title";title.textContent=s.title;playButton.onclick=()=>{loadSong(i);audio.play().catch(()=>{});};title.onclick=()=>loadSong(i);row.append(playButton,title);trackList.appendChild(row);});loadSong(0);}

/* ??? — em qualquer aba abre o vídeo em tela cheia e depois volta normalmente */
const overlay=document.getElementById("videoOverlay"),video=document.getElementById("mysteryVideo");
function playMystery(){if(!overlay||!video)return;overlay.classList.remove("hidden");video.currentTime=0;video.play().catch(()=>{});}
function stopMystery(){if(!overlay||!video)return;video.pause();video.currentTime=0;overlay.classList.add("hidden");}
document.querySelectorAll(".mysteryBtn").forEach(b=>b.addEventListener("click",playMystery));
const skipVideo=document.getElementById("skipVideo");if(skipVideo)skipVideo.onclick=stopMystery;if(video)video.addEventListener("ended",stopMystery);
const gameBox=document.querySelector(".game-box"),gamePlay=document.querySelector(".game-play");if(gameBox)gameBox.addEventListener("touchstart",()=>gameBox.classList.add("touched"),{passive:true});if(gamePlay)gamePlay.onclick=()=>{window.location.href="streak/jogo1.html";};
